// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcDSc9OwY1mVMe89y7nEMmQR3FvvxtCo',
    appId: '1:444403602536:web:259912521942be561597dd',
    messagingSenderId: '444403602536',
    projectId: 'chat-school-5c241',
    authDomain: 'chat-school-5c241.firebaseapp.com',
    storageBucket: 'chat-school-5c241.appspot.com',
    measurementId: 'G-RQFKQS3K1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzg54BzGeB5efPFIojL4KaTwrvR7Utn88',
    appId: '1:444403602536:android:c7b7d9fa1f81d79f1597dd',
    messagingSenderId: '444403602536',
    projectId: 'chat-school-5c241',
    storageBucket: 'chat-school-5c241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QeZj7_26iv4QzjuPmLuV12hws68UQ50',
    appId: '1:444403602536:ios:c1aa80b7f64af6a21597dd',
    messagingSenderId: '444403602536',
    projectId: 'chat-school-5c241',
    storageBucket: 'chat-school-5c241.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QeZj7_26iv4QzjuPmLuV12hws68UQ50',
    appId: '1:444403602536:ios:7891b9d0925a5d861597dd',
    messagingSenderId: '444403602536',
    projectId: 'chat-school-5c241',
    storageBucket: 'chat-school-5c241.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
